# https://jekyllrb.com/
# https://github.com/jekyll/minima
remote_theme: jekyll/minima
title: evnl.me
author:
  name: Evan Lee
  # email: 112362737+evnlme@users.noreply.github.com
description: >-
  Sustainable and reproducible systems for everyone.
  Overcoming entropy through organization.
  The personal reality of Evan Lee and the random stuff he thinks about.

minima:
  skin: dark

  social_links:
  - platform: github
    user_url: https://github.com/evnlme