# https://jekyllrb.com/
# https://github.com/jekyll/minima
remote_theme: jekyll/minima
title: evnl.me
author:
  name: Evan Lee
  # email: 112362737+evnlme@users.noreply.github.com
description: >-
  Sustainable and reproducible systems.
  Evolution without entropy.
  Function without form.
  The personal reality of Evan Lee and the random stuff he thinks about
  such as building utopias, living forever,
  and engineering himself out of the system.

minima:
  skin: dark

  social_links:
  - platform: github
    user_url: https://github.com/evnlme

header_pages:
- reading-list.md