# https://github.com/jekyll/minima
remote_theme: jekyll/minima
title: evnl.me
author:
  name: Evan Lee
  # email: 112362737+evnlme@users.noreply.github.com
description: >-
  Perception is everything.

minima:
  skin: solarized-dark