# https://jekyllrb.com/
# https://github.com/jekyll/minima
remote_theme: jekyll/minima
title: evnl.me
author:
  name: Evan Lee
  # email: 112362737+evnlme@users.noreply.github.com
description: >-
  Evan's personal site.
  He wants to conquer his subconscious
  and learn to perceive things he couldn't perceive before.
  Is the subconscious truly bottomless?

minima:
  skin: dark

  social_links:
  - platform: github
    user_url: https://github.com/evnlme

header_pages:
- lists.md

include:
- "_sitemap.txt"

google_analytics: G-WK15EWYH7V
